blank_issues_enabled: true
contact_links:
    - name: General Question
      url: https://github.com/SalyyS1/SLTerm/discussions
      about: Have a question on something? Start a new discussion thread.
    - name: Engage with us directly on Discord
      url: https://discord.gg/XfvZ334gwU
      about: Join our Discord server to get updates on new features, bug fixes, and more.
    - name: Review open issues
      url: https://github.com/SalyyS1/SLTerm/issues
      about: Please check if your issue isn't already there.
